version: '3.8'

services:
  vue-sample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-sample
    volumes:
      - ..:/mnt
      - volume_trick:/mnt/app/node_modules
    working_dir: /mnt
    ports:
      - 3000:3000
    tty: true

volumes:
  volume_trick: